// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twmbmtszpzhhrtteqegd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3bWJtdHN6cHpoaHJ0dGVxZWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzQxNzAsImV4cCI6MjA2OTcxMDE3MH0.QzD4TmrvmTQwtH6MA7jHGdKsUTxT2GpeprT95p_QY1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});